GOOGLE_API_KEY = 'AIzaSyCDGfKO-nP8vs-_Qpy2wNXE2PqpDE1zO38'
SEARCH_TIME_LIMIT = 30  # search time limit in seconds
LOG_SEARCH = False
GOOGLE_API_USED = 'DIRECTIONS'    # DIRECTIONS or MATRIX
SEARCH_STRATEGY = 'QUASI'   # QUASI or GLOBAL,